/*
 * ultra_sonic.h
 *
 *  Created on: Oct 14, 2024
 *      Author: user
 */

#ifndef ULTRA_SONIC_H_
#define ULTRA_SONIC_H_



#include "std_types.h"


#define TRIGGER_PIN_ID   PIN7_ID
#define TRIGGER_PORT_ID  PORTD_ID
#define ECHO_PIN_ID      PIN6_ID
#define ECHO_PORT_ID     PORTD_ID



/*
 * Description:
 * Initialize the Ultrasonic sensor driver:
 * - Initialize the ICU driver.
 * - Set the ICU callback function.
 * - Set the direction for the trigger pin as output.
 */
void Ultrasonic_init(void);

/*
 * Description:
 * Send a trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description:
 * Get the measured distance from the ultrasonic sensor:
 * - Send the trigger pulse.
 * - Start the measurement process through the ICU.
 * - Return the measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description:
 * Callback function for ICU.
 * - Calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);




#endif /* ULTRA_SONIC_H_ */
